### ISSUE TITLE
How to use mobilenet_v2 model

### ISSUE THREAD

**Issue by OctaM** [kamwoh/Car-Model-Classification#1]
Hello, 

I manage to run the eval with resnext model and I was wandering if there is a way to do the same with mobilenet_v2 since there is no config file for this model. 

Should I use the restnext's config for mobilenet as well? I tried that but I got some errors about some missing layers.

Thanks

**Comment by kamwoh** [comment]
hi, the config file should change the architecture keyword from resnext to mobilenet as well

"arch": "resnext50" -> "arch": "mobilenetv2"
